# Site settings
baseurl = "https://rogiersbart.github.io/weekly/"
languageCode = "en-uk"
title = "weekly"
theme = "hugrid"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-XXXXXXXX-Y"

contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "docs"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
    # Meta
    title = "<img src='logo.png' style='height:15rem;'><br>[weekly](https://rogiersbart.github.io/weekly)"
    subtitle = "One hundred photographs<br><button style='background-color:#f8f8f8;border: 1px solid transparent;border-color:#e7e7e7;padding: 0.375rem 0.75rem;font-size: 1rem;line-height: 1.5;border-radius: 0.25rem;cursor: pointer;'>[rogiersbart.github.io](https://rogiersbart.github.io/)</button>"
    author = "Bart Rogiers [rogiersbart]"
    description = ""
    keywords = ""

    # Body background color
    bodybgcolor = "#ffffff"

    # Preview container button text
    buttontext = "Source"

    # Footer text
    footertext = '<center><p xmlns:dct="http://purl.org/dc/terms/" xmlns:cc="http://creativecommons.org/ns#" class="license-text">This work by <a rel="cc:attributionURL dct:creator" property="cc:attributionName" href="https://rogiersbart.github.io/">Bart Rogiers</a> is licensed under <a rel="license" href="https://creativecommons.org/licenses/by/4.0">CC BY 4.0.</a></p></center><br>'

    # add extra-css
    # custom_css = ["css/extra1.css", "css/extra2.css"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
